before_script:
  - apt-get update
  - apt-get install npm

stages:
  - build
  
build:
  stage: build
  image: microsoft/dotnet:latest
  script: 
    - dotnet publish Rodgort -c Release
  artifacts:
    paths:
      - StackExchangeApi/bin/Release/netcoreapp2.1/publish/*.*