before_script:
  - apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - apt-get update
  - sudo apt-get install -y nodejs

stages:
  - build
  
build:
  stage: build
  image: microsoft/dotnet:latest
  script: 
    - dotnet publish Rodgort -c Release
  artifacts:
    paths:
      - StackExchangeApi/bin/Release/netcoreapp2.1/publish/*.*