stages:
  - build
  
build:
  stage: build
  image: microsoft/dotnet:latest
  script: 
    - dotnet publish -c Release
  artifacts:
    paths:
      - StackExchangeApi/bin/Release/netcoreapp2.1/publish/*.*