before_script:
  - apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get update
  - apt-get install -y nodejs

stages:
  - build
  
build:
  stage: build
  image: microsoft/dotnet:latest
  script: 
    - dotnet publish Rodgort -c Release
  artifacts:
    paths:
      - Rodgort/bin/Release/netcoreapp2.1/publish/*.*